services:
  db:
    image: postgres:15
    container_name: task_automation_db
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_pass
      POSTGRES_DB: task_automation_db
    volumes:
      - task_automation_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    container_name: task_automation_api
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8001:8000"

volumes:
  task_automation_postgres_data: